config/routes.rb
Toadstool::Application.routes.draw do
  namespace :admin do
    ['color_palettes', 'forms', 'grids', 'typography', 'modules', 'patterns'].each do |action|
      get "/styleguide/#{action}" => "styleguide##{action}"
    end
    get '/styleguide' => 'styleguide#typography'

    get '/styleguide/examples/*example' => 'styleguide/examples#show', :as  => :styleguide_example
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base
end

app/controllers/admin/styleguide/examples_controller.rb
class Admin::Styleguide::ExamplesController < Admin::AdminController

  layout 'styleguide'

  def show
    @example = Styleguide::FileLocator.get(params[:example], params[:format])
    @data = Styleguide::Fixtures.get(params[:example]) if module?
  end

  private

  def module?
    params[:format] == 'module'
  end
end

app/controllers/admin/styleguide_controller.rb
class Admin::StyleguideController < Admin::AdminController
  layout 'styleguide'

  def typography
  end

  def grids
  end

  def color_palettes
  end

  def forms
  end

  def modules
    @presenter = Styleguide::ModulesPresenter.new(Styleguide::FileLocator.modules)
  end

  def patterns
    @presenter = Styleguide::PatternsPresenter.new(Styleguide::FileLocator.patterns)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/styleguide_helper.rb
module StyleguideHelper

  def sass_example(file)
    style = stylesheet(file)
    code_toggle sass_file(style) if File.exists?(style)
  end

  def sass_full_path_example(file)
    code_toggle sass_file(File.new(file)) if File.exists?(file)
  end

  def scss_example(file)
    style = stylesheet(file, '.scss')
    code_toggle sass_file(style) if File.exists?(style)
  end

  def html_example(file_name, directory = '')
    file = haml_file(file_name, directory)
    render :partial => 'admin/styleguide/html_example', :locals => file_hash(file)
  end

  def code_toggle(file)
    render :partial => 'admin/styleguide/code_toggle', :locals => file_hash(file)
  end

  def example_file(file_name)
    file = File.new(file_name)
    render :partial => 'admin/styleguide/module_example', :locals => file_hash(file)
  end

  private

  def stylesheet(file, ext = '.sass')
    File.join(Rails.root, 'app', 'assets', 'stylesheets', file + ext)
  end

  def sass_file(style_path)
    File.new(style_path)
  end

  def haml_file(file_name, directory)
    File.new(File.join(Rails.root, 'app', 'views', 'admin', 'styleguide', directory, file_name + '.html.haml'))
  end

  def file_hash(file)
    { :content => file.read(), :mtime => file.mtime, :path => relative_path(file.path) }
  end

  def relative_path(file_path)
    Pathname.new(file_path).relative_path_from(Rails.root).to_s
  end
end

app/views/admin/styleguide/_code_toggle.html.haml
.example_code
  %p.codeToggle
    %a{:href => "#"} view
  %pre.prettyprint.linenums.hidden{:contenteditable => true}
    != content
  %p= path
  %p.mtime
    Last modified: #{mtime}

app/views/admin/styleguide/_example_list.haml
%div.dashboard-wrapper
  - @presenter.categories.each do |category|
    %div
      %h4= category.display_name
      - category.files.each do |file|
        %ul
          %li= link_to file.display_name, admin_styleguide_example_path(:example => file.slug)

app/views/admin/styleguide/_html_example.html.haml
%article.element_example
  = Haml::Engine.new(content).render
= render :partial => 'admin/styleguide/code_toggle', :locals => { :content => content, :path => path, :mtime => mtime}

app/views/admin/styleguide/_module_example.html.haml
%article.element_example
= render :partial => 'admin/styleguide/code_toggle', :locals => { :content => content, :path => path, :mtime => mtime}

app/views/admin/styleguide/_subheader.html.haml
%header.toadstool_subheader
  %h2= header
  %article
    %p!= text

app/views/admin/styleguide/color_palettes.html.haml
%header.toadstool_header
  %h1 colors
%article.colorcode
  %header.toadstool_subheader
    %h2 Typography
  .primary_header_color
    %p $primary_header_color
  .primary_text
    %p $primary_text
  .secondary_text
    %p $secondary_text
  .href_color
    %p $href_color
%article.colorcode
  %header.toadstool_subheader
    %h2 Borders, rules and shadows
  .shadow_color
    %p $shadow_color
  .border_color
    %p $border_color
  .standard_hr_color
    %p $standard_hr_color
  .standard_border_color
    %p $standard_border_color

%article.colorcode
  %header.toadstool_subheader
    %h2 Swatch Pattern
  .alpha_texture
    %p %alpha_texture

%article.colorcode
  %header.toadstool_subheader
    %h2 Form elements
  .alert_background_color
    %p $alert_background_color
  .input_disabled
    %p $input_disabled
  .input_disabled_bkg
    %p $input_disabled_bkg
  .input_disabled_border
    %p $input_disabled_border
  .input_disabled_text
    %p $input_disabled_text
  .form_field_background_color
    %p $form_field_background_color
  .form_field_focus_color
    %p $form_field_focus_color
  .form_field_fail_bkg
    %p $form_field_fail_bkg
  .form_field_border
    %p $form_field_border
  .form_field_border_fail
    %p $form_field_border_fail
  .form_field_focus_border_color
    %p $form_field_focus_border_color
  .form_field_text_fail
    %p $form_field_text_fail
  .form_label_color
    %p $form_label_color
  .optional_field_text_color
    %p $optional_field_text_color
  .instructional_text
    %p $instructional_text
  .placeholder_text
    %p $placeholder_text
  .inline_alert_bkg_color
    %p $inline_alert_bkg_color
  .inline_alert_text_color
    %p $inline_alert_text_color
%article.colorcode
  %header.toadstool_subheader
    %h2 Buttons
  .button_color
    %p $button_color
  .secondary_button_border_color
    %p $secondary_button_border_color
  .button_text
    %p $button_text
%article.colorcode
  %header.toadstool_subheader
    %h2
      HTML5 colors
      %a{:href => "#"} (view all)
  .webkit_tap_hightlight
    %p $webkit_tap_hightlight
  %section.hidden
    .ins_color
      %p $ins_color
    .selection_color
      %p $selection_color
    .selection_text_color
      %p $selection_text_color
    .mark_color
      %p $mark_color
%article.colorcode
  %header.toadstool_subheader
    %h2
      grayscale
      %a{:href => "#"} (view all)
  .alpha_gray
    %p $alpha_gray
  %section.hidden
    .bravo_gray
      %p $bravo_gray
    .charlie_gray
      %p $charlie_gray
    .delta_gray
      %p $delta_gray
    .echo_gray
      %p $echo_gray
    .fox_gray
      %p $fox_gray
    .golf_gray
      %p $golf_gray
    .hotel_gray
      %p $hotel_gray
    .india_gray
      %p $india_gray
    .white
      %p $white
%article.colorcode
  %header.toadstool_subheader
    %h2
      alpha color scale
      %a{:href => "#"} (view all)
  .alpha_color
    %p $alpha_color
  %section.hidden
    .alpha_color_bravo
      %p $alpha_color_bravo
    .alpha_color_charlie
      %p $alpha_color_charlie
    .alpha_color_delta
      %p $alpha_color_delta
    .alpha_color_echo
      %p $alpha_color_echo
    .alpha_color_fox
      %p $alpha_color_fox
    .alpha_color_golf
      %p $alpha_color_golf
    .alpha_color_hotel
      %p $alpha_color_hotel
    .alpha_color_india
      %p $alpha_color_india
    .alpha_color_juliet
      %p $alpha_color_juliet
%article.colorcode
  %header.toadstool_subheader
    %h2
      bravo color scale
      %a{:href => "#"} (view all)
  .bravo_color
    %p $bravo_color
  %section.hidden
    .bravo_color_bravo
      %p $bravo_color_bravo
    .bravo_color_charlie
      %p $bravo_color_charlie
    .bravo_color_delta
      %p $bravo_color_delta
    .bravo_color_echo
      %p $bravo_color_echo
    .bravo_color_fox
      %p $bravo_color_fox
    .bravo_color_golf
      %p $bravo_color_golf
    .bravo_color_hotel
      %p $bravo_color_hotel
    .bravo_color_india
      %p $bravo_color_india
    .bravo_color_juliet
      %p $bravo_color_juliet
%article.colorcode
  %header.toadstool_subheader
    %h2
      charlie color scale
      %a{:href => "#"} (view all)
  .charlie_color
    %p $charlie_color
  %section.hidden
    .charlie_color_bravo
      %p $charlie_color_bravo
    .charlie_color_charlie
      %p $charlie_color_charlie
    .charlie_color_delta
      %p $charlie_color_delta
    .charlie_color_echo
      %p $charlie_color_echo
    .charlie_color_fox
      %p $charlie_color_fox
    .charlie_color_golf
      %p $charlie_color_golf
    .charlie_color_hotel
      %p $charlie_color_hotel
    .charlie_color_india
      %p $charlie_color_india
    .charlie_color_juliet
      %p $charlie_color_juliet
%article.colorcode
  %header.toadstool_subheader
    %h2
      delta color scale
      %a{:href => "#"} (view all)
  .delta_color
    %p $delta_color
  %section.hidden
    .delta_color_bravo
      %p $delta_color_bravo
    .delta_color_charlie
      %p $delta_color_charlie
    .delta_color_delta
      %p $delta_color_delta
    .delta_color_echo
      %p $delta_color_echo
    .delta_color_fox
      %p $delta_color_fox
    .delta_color_golf
      %p $delta_color_golf
    .delta_color_hotel
      %p $delta_color_hotel
    .delta_color_india
      %p $delta_color_india
    .delta_color_juliet
      %p $delta_color_juliet
%article.colorcode
  %header.toadstool_subheader
    %h2
      echo color scale
      %a{:href => "#"} (view all)
  .echo_color
    %p $echo_color
  %section.hidden
    .echo_color_bravo
      %p $echo_color_bravo
    .echo_color_charlie
      %p $echo_color_charlie
    .echo_color_delta
      %p $echo_color_delta
    .echo_color_echo
      %p $echo_color_echo
    .echo_color_fox
      %p $echo_color_fox
    .echo_color_golf
      %p $echo_color_golf
    .echo_color_hotel
      %p $echo_color_hotel
    .echo_color_india
      %p $echo_color_india
    .echo_color_juliet
      %p $echo_color_juliet

app/views/admin/styleguide/examples/show.haml
%div.toadstool_header.toadstool_subheader
  :markdown
    #{@example.markdown}

%article.element_example
  = render :partial => @example.partial, :locals => @data

= example_file @example.full_path
- @example.sass_path.each do |path|
  = sass_full_path_example path

app/views/admin/styleguide/forms.html.haml
%header.toadstool_header
  %h1 form

%section#primary_buttons
  - text = 'Use defualt semantic HTML to create the following buttons.'
  = render :partial => 'admin/styleguide/subheader', :locals => { :header => 'Primary Buttons', :text => text }

  = html_example 'forms/ui_patterns/_primary_buttons'

  = sass_example '_buttons'
  = scss_example 'buttons/_mixins'
  = scss_example 'buttons/_extends'

%footer.toadstool_footer

app/views/admin/styleguide/forms/ui_patterns/_primary_buttons.html.haml
%form
  %fieldset
    %a.button Button
    %button Button
    %a.button Button
    %button Button

app/views/admin/styleguide/grids.html.haml
%header.toadstool_header
  %h1 grids

= render :partial => "admin/styleguide/grids/use_definition"

%article.element_example.col_12_grid.shift
  %ul
    %li.grid-1 1 col
    %li.grid-11 11 col
  %ul
    %li.grid-2 2 col
    %li.grid-10 10 col
  %ul
    %li.grid-3 3 col
    %li.grid-9 9 col
  %ul
    %li.grid-4 4 col
    %li.grid-8 8 col
  %ul
    %li.grid-5 5 col
    %li.grid-7 7 col
  %ul
    %li.grid-6 6 col
    %li.grid-6 6 col
  %ul
    %li.grid-7 7 col
    %li.grid-5 5 col
  %ul
    %li.grid-8 8 col
    %li.grid-4 4 col
  %ul
    %li.grid-9 9 col
    %li.grid-3 3 col
  %ul
    %li.grid-10 10 col
    %li.grid-2 2 col
  %ul
    %li.grid-11 11 col
    %li.grid-1 1 col
  %ul
    %li.grid-12 12 col
%article.element_example.col_10_grid
  %ul
    %li.grid-1 1 col
    %li.grid-9 9 col
  %ul
    %li.grid-2 2 col
    %li.grid-8 8 col
  %ul
    %li.grid-3 3 col
    %li.grid-7 7 col
  %ul
    %li.grid-4 4 col
    %li.grid-6 6 col
  %ul
    %li.grid-5 5 col
    %li.grid-5 5 col
  %ul
    %li.grid-6 6 col
    %li.grid-4 4 col
  %ul
    %li.grid-7 7 col
    %li.grid-3 3 col
  %ul
    %li.grid-8 8 col
    %li.grid-2 2 col
  %ul
    %li.grid-9 9 col
    %li.grid-1 1 col
  %ul
    %li.grid-10 10 col
    %li.grid-11 11 col
    %li.grid-12 12 col
%article.element_example.col_4_grid
  %ul
    %li.grid-1 1 col
    %li.grid-3 3 col
  %ul
    %li.grid-2 2 col
    %li.grid-2 2 col
  %ul
    %li.grid-3 3 col
    %li.grid-1 1 col
  %ul
    %li.grid-4 4 col
    %li.grid-5 5 col
    %li.grid-6 6 col
    %li.grid-7 7 col
    %li.grid-8 8 col
    %li.grid-9 9 col
    %li.grid-10 10 col
    %li.grid-11 11 col
    %li.grid-12 12 col

= render :partial => "admin/styleguide/grids/grid_arguments"

app/views/admin/styleguide/grids/_grid_arguments.html.haml
%section#grid_arguments
  %header.toadstool_subheader
    %h2 grid arguments
    %article
      %p
        Additional arguments can be passed into the grid mixin to include
        %code $grid_padding_l, $grid_padding_r, $grid_padding_tb, $grid_border, $grid_uom, $col_gutter, $grid_type, $grid_align, $grid_context
      %ul
        %li
          %code $grid_padding_l
          %span adds padding LEFT, takes integer value
        %li
          %code $grid_padding_r
          %span adds padding RIGHT, takes integer value
        %li
          %code $grid_padding_tb
          %span adds padding TOP and BOTTOM, takes integer value
        %li
          %code $grid_border
          %span takes integer value, adds border using
          %code $border_color
          and
          %code $standard_border_style
          configs found in
          = succeed "." do
            %code _config.scss
        %li
          %code $border_place
          %span options are
          %code left
          and
          = succeed "." do
            %code right
          Argument will place a single border on either the left or right side of the block.
        %li
          %code $grid_uom
          %span set to percent by default, accepts
          %code em
          as argument.
        %li
          %code $col_gutter
          %span takes integer to adjust col gutter
        %li
          %code $grid_type
          %span set to 12 col by default, allows for on-the-fly adjustment to grid type
          %b Feature is currently inoperable
        %li
          %code $grid_align
          %span takes
          %code center
          as argument
        %li
          %code $grid_context
          %span Adjusts column widths based on nested grid context. Necessary when calcuclating with percentages
      %p
        Stipe uses the
        %code box-size
        CSS property, but this is not supported by IE7. By entereing values like
        = succeed "," do
          %code $grid_padding_l, $grid_padding_r, $grid_border
        Stipe will calculate a width that IE7 can use.

app/views/admin/styleguide/grids/_use_definition.html.haml
%section#grid_use_definition
  %header.toadstool_subheader
    %h2 grid use definition
    %article
      %p To use grids in Toadstool, Stipe comes with some awesome Mixins for easy creation of custom grids as well as commonly used silent classes.
      %p
        Stipe's grid system is based on the original 960.gs solution; there are concepts like columns, gutters and nesting. For the most part when framing a UI, simply extend already pre-defined
        %a{:href => "http://goo.gl/W1QlA", :target => "_blank"} silent classes
        like
        = succeed "." do
          %code @extend %grid_4
        These pre-formatted silent classes already come with additional support for mobile devices.
      %p
        If you require more customization of a given grid, use
        = succeed "," do
          %code @include grid($col_count)
        replacing
        %code $col_count
        with the number of colums you need.
      %p
        For nested grids, Stipe supports 'alpha' and 'omega' concepts. For added spice, if you want to remove both margins, 'alphaomega' works too. Example
        = succeed "." do
          %code @include grid(5, alpha)
      %p
        Since Stipe's grid is pure math, you can pass in floating point numbers as well. Example, using
        %code @include grid(12, alphaomega)
        will remove the margin on the outside of the grid, but will not be 100% across. Increasing the value fractionally (
        %code> @include grid(12.25, alphaomega)
        ) will address the missing space.

app/views/admin/styleguide/modules.html.haml
%header.toadstool_header
  %h1 modules

= render :partial => 'admin/styleguide/example_list', :locals => { :presenter => @presenter }

.markdown-content
  :markdown
    #{File.new(File.join(Rails.root,'app/views/application/modules/readme.md')).read}

app/views/admin/styleguide/patterns.html.haml
%header.toadstool_header
  %h1 Ui patterns

= render :partial => 'admin/styleguide/example_list', :locals => { :presenter => @presenter }

.markdown-content
  :markdown
    #{File.new(File.join(Rails.root,'app/views/admin/styleguide/ui_patterns/readme.md')).read}

app/views/admin/styleguide/typography.html.haml
%header.toadstool_header
  %h1 typography

%section#generalTypography
  - text = "Toadstool's typograhy is mainly maintained via the <code>_config.scss</code> file. For more detailed information, see <a href='http://goo.gl/Hl8po' target='_blank'>Stipe's typography documentation.</a>"
  = render :partial => 'admin/styleguide/subheader', :locals => { :header => 'general typography', :text => text }

  = html_example 'typography/_body_copy'
  = sass_example '_typography'
  = sass_example '_config'


%section#headings
  - text = "In Toadstool, presentation is 100% separated from content and markup, this goes for typography too. Heading styles are not beholden to heading tags, but applied via slient classes to the appropriate semantic markup or class as needed."
  = render :partial => 'admin/styleguide/subheader', :locals => {  :header => 'headings', :text => text }

  = html_example 'typography/_headings'
  = sass_example '_typography'
  = sass_example '_config'

%section#heading_groups
  - text = "Special typography charasteristics based on placement in heading groups."
  = render :partial => 'admin/styleguide/subheader', :locals => {  :header => 'heading groups', :text => text }

  = html_example 'typography/ui_patterns/_hgroups'
  = sass_example '_typography'

%section#header_copy_link
  - text = "UI pattern grouping to include a header, body copy and a link."
  = render :partial => 'admin/styleguide/subheader', :locals => {  :header => 'header, copy and link', :text => text }

  = html_example 'typography/ui_patterns/_header_copy_link'
  = sass_example '_typography'

%section#section_title
  - text = "UI pattern for section titles"
  = render :partial => 'admin/styleguide/subheader', :locals => {  :header => 'section title', :text => text }

  = html_example 'typography/ui_patterns/_section_title'
  = sass_example '_typography'

%section#ico-fonts
  - header = "Substantial ico-font library"
  - text = ""
  = render :partial => 'admin/styleguide/subheader', :locals => {  :header => header, :text => text }

  .markdown-content
    :markdown
      #{File.new(File.join(Rails.root,'app/views/admin/styleguide/typography/ico-fonts.md')).read}

  = html_example 'typography/ui_patterns/_ico_fonts'
  = scss_example 'typography/_ico-fonts'
  = scss_example 'typography/_extends'

%footer.toadstool_footer

app/views/admin/styleguide/typography/_body_copy.html.haml
%p Sapiente enim fingerstache, etsy single-origin coffee truffaut sriracha cupidatat viral hella eiusmod whatever. Salvia deserunt terry richardson nostrud irure marfa. Portland sapiente authentic swag. Anim narwhal exercitation consectetur butcher. Pork belly yr banksy occupy twee consectetur. Sustainable cupidatat eiusmod tumblr pour-over brooklyn keffiyeh, DIY 8-bit ex brunch single-origin coffee duis seitan. Mixtape ea 8-bit ennui, viral voluptate authentic culpa aesthetic occaecat art party.
%p Master cleanse swag officia selvage ea. Laborum fingerstache non quinoa cliche skateboard aliquip, irony portland. Fixie nihil godard, quis incididunt lomo locavore non quinoa iphone excepteur. Aute mollit food truck, voluptate occupy sed gastropub nostrud banh mi. Narwhal fugiat gluten-free, thundercats ennui lo-fi DIY kale chips nisi. Reprehenderit ea scenester, minim exercitation pork belly ut odd future iphone nostrud nihil. Ethical voluptate seitan high life.

app/views/admin/styleguide/typography/_headings.html.haml
%h1 Synth ethnic laborum seitan, assumenda nostrud DIY mustache blue bottle
%h2 Mlkshk culpa skateboard, carles pickled
%h3 food truck mustache consequat irony
%h4 Church-key odio squid, kogi bushwick
%h5 Pork belly cillum synth, shoreditch nulla est bicycle

app/views/admin/styleguide/typography/ui_patterns/_header_copy_link.html.haml
%hgroup
  %h2 DETAIL PAGE HEADER TITLE (I.E, “CHEFSTEPS”)
  %h5 Detailed page short description

// Module will support headings h1 - h3 for SEO and maintain a consistent style
%article.body-article
  %h1 secondary header title for paragraph below
  %h2 secondary header title for paragraph below
  %h3 secondary header title for paragraph below
  %p Neutra flexitarian jean shorts meggings irony odd future, leggings squid aesthetic 8-bit. Leggings PBR swag readymade etsy mustache. Gastropub deep v put a bird on it, thundercats keytar pitchfork pop-up. Fixie 3 wolf moon letterpress, blue bottle selfies ethnic four loko deep v cliche.
  %p
    %a{:href => "#"} Example of body text link

app/views/admin/styleguide/typography/ui_patterns/_hgroups.html.haml
%hgroup
  %h1 PAGE HEADER TITLE (I.E, CONTACT)
  %h4 Page subheader title, short description.

%hgroup
  %h2 DETAIL PAGE HEADER TITLE (I.E, “CHEFSTEPS”)
  %h5 Detailed page short description

.blog-hgroup
  %span 1.1.13
  %h1 Artifex Press Launches Digital Catalogues Raisonnés Platform
  %h5
    by
    %a{:href => "/"} this person

app/views/admin/styleguide/typography/ui_patterns/_ico_fonts.html.haml
// To add a new icon fonts to the view, simply add the name of the new font to the `icons` list
// ---------------------------------------------------
- icons = 'icon-01', 'icon-02'

// DO NOT EDIT
// ---------------------------------------------------
- icons.each do |icon|
  %span{"aria-hidden" => "true", :class => icon}

app/views/admin/styleguide/typography/ui_patterns/_section_title.html.haml
%h1.section-title
  fashion axe enim tattooed butcher

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Toadstool</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/styleguide.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0, minimum-scale=0.5 maximum-scale=1.0"}

    = stylesheet_link_tag :application
    = stylesheet_link_tag :toadstool
    = javascript_include_tag :toadstool

  %body{:onload => 'prettyPrint()'}

    %section.styleguide_main_content
      %header.toadstool_main_header
        %h1 website.com
        %button.nav_toggle
          %span

      %nav.toadstool_nav.mobi_hidden
        %ol
          %li= link_to_unless_current 'Typography', admin_styleguide_typography_path
          %li= link_to_unless_current 'Grids', admin_styleguide_grids_path
          %li= link_to_unless_current 'Color palettes', admin_styleguide_color_palettes_path
          %li= link_to_unless_current 'Forms', admin_styleguide_forms_path
          %li= link_to_unless_current 'Modules', admin_styleguide_modules_path
          %li= link_to_unless_current 'UI Patterns', admin_styleguide_patterns_path

      %article.styleguide_article
        = yield

      %footer.toadstool_main_footer
        &copy; 2012 -
        %script
          var currentDate = new Date()
          var year = currentDate.getFullYear()
          document.write(year)

        %a{:href => "https://github.com/Anotheruiguy/toadstool"} Fork Toadstool
        on Github.
        It is available for use and modification under the
        %a{ :href => "https://github.com/Anotheruiguy/toadstool/blob/master/doc-src/mit_license.md"} MIT license

    .emBox
      %span.screen-width 0
      /
      %span.screen-width-px 0